# Generated by Django 5.0.6 on 2024-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('Entry-Level', 'Entry-Level'), ('Mid-Level', 'Mid-Level'), ('Senior-Level', 'Senior-Level')], max_length=50)),
                ('employment_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('FL', 'Freelance'), ('IN', 'Internship')], default='FT', max_length=2)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobFields1',
        ),
        migrations.DeleteModel(
            name='JobFields2',
        ),
    ]
