# Generated by Django 5.0.6 on 2024-08-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Country',
            field=models.CharField(choices=[('----', '----'), ('India', 'India'), ('United States', 'United States'), ('Canada', 'Canada'), ('Others', 'Others')], default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_Number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=10),
        ),
    ]
